export const actions = {
	GET_RANDOM_USERS: "GET_RANDOM_USERS",
	GET_RANDOM_USERS_PENDING: "GET_RANDOM_USERS_PENDING",
	GET_RANDOM_USERS_FULFILLED: "GET_RANDOM_USERS_FULFILLED",
	GET_RANDOM_USERS_REJECTED: "GET_RANDOM_USERS_REJECTED"
};